[globals]
DEBUG=3
UI=app/views/
AUTOLOAD=app/controllers/|app/models/

; Konfigurasi Database MySQL Utama
db_dns=mysql:host=localhost;port=3306;dbname=mini_opti_tracker;charset=utf8mb4
db_user=root
db_pass=

; Konfigurasi Database Eksternal Sekretariat (Surat Masuk)
db_sekretariat_dns=mysql:host=localhost;port=3306;dbname=db_sekretariat;charset=utf8mb4
db_sekretariat_user=root
db_sekretariat_pass=
db_sekretariat_table=surat_masuk

