[globals]
DEBUG=3
UI=app/views/
AUTOLOAD=app/controllers/|app/models/

; Konfigurasi Database MySQL
db_dns=mysql:host=localhost;port=3306;dbname=mini_opti_tracker;charset=utf8mb4
db_user=root
db_pass=
